### ISSUE TITLE
加一个mod支持按钮呗

### ISSUE THREAD

**Issue by WangYneos** [sht2017/MCBE-Fast-deploy-server-on-linux#1]
【x】to add mods supports
wget https://github.com/Sysca11/bdlauncher/archive/master.zip
unzip master.zip
cp -a ./xxx/bin/launcher.so ./
rm -rf ./xxx/bin/launcher.so
cp -a ./xxx/bin/* ./mods

**Comment by sht2017** [comment]
这种方式是用hook动态劫持函数然后作为api开放的吧

**Comment by sht2017** [comment]
十分感谢 已mark 后期会加入

**Comment by sht2017** [comment]
可能会需要一段时间对bdsmod进行稳定评估性测试后才会加入 望谅解
